topic_names = {0:u'sushi',
               1:u'chicken & waffle',
               2:u'bars',
               3:u'indian',
               4:u'family',
               5:u'delivery',
               6:u'chinese & korean',
               7:u'mexican',
               8:u'cleaniless',
               9:u'bbq',
               10:u'spanish',
               11:u'vegetarian',
               12:u'favorite places',
               13:u'new experience',
               14:u'popular places',
               15:u'quebec food',
               16:u'seafood & outdoor',
               17:u'worth it',
               18:u'steakhouse',
               19:u'nonsensical',
               20:u'mexican & peruvian',
               21:u'hawaiian',
               22:u'friendly',
               23:u'fish & chip',
               24:u'vietnamese & thai',
               25:u'bar & nightlife',
               26:u'burger',
               27:u'bad',
               28:u'family meal',
               29:u'italian',
               30:u'hawaiian',
               31:u'lobster',
               32:u'vegas',
               33:u'decor',
               34:u'noise',
               35:u'dessert',
               36:u'pizza',
               37:u'family chain restaurants',
               38:u'beer',
               39:u'place to visit',
               40:u'food court',
               41:u'quality',
               42:u'mexican',
               43:u'price',
               44:u'salad & lunch',
               45:u'lunch & dinner',
               46:u'breakfast',
               47:u'wings',
               48:u'atmosphere',
               49:u'sandwiches & bakery'}


